spring:
  jpa:
    database: postgresql

    # Suppress Postgres JPA Error:
    # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
    properties.hibernate:
      temp.use_jdbc_metadata_defaults: false
      jdbc.time_zone: UTC
    open-in-view: false
    show-sql: false

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/imagilabs}
    username: ${JDBC_DATABASE_USERNAME:imagilabs}
    password: ${JDBC_DATABASE_PASSWORD:imagilabs}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:}

jwt:
  ttl-web: ${JWT_TTL_WEB:P30D}
  ttl-mobile: ${JWT_TTL_MOBILE:P30D}

---

spring:
  config:
    activate:
      on-profile: prod

  mail:
    host: ${MAIL_HOST:}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
