spring:
  jpa:
    database: postgresql

    properties:
      hibernate:
        # Suppress Postgres JPA Error:
        # Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        temp.use_jdbc_metadata_defaults: false
        jdbc.time_zone: UTC
        show_sql: false
    open-in-view: false

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/imagilabs}
    username: ${JDBC_DATABASE_USERNAME:imagilabs}
    password: ${JDBC_DATABASE_PASSWORD:imagilabs}

  ai:
    openai:
      api-key: ${SPRING_OPEN_AI_API_KEY:}
      chat:
        options:
          model: ${SPRING_OPEN_AI_MODEL:gpt-4o-mini}
          temperature: 0.6
      tip-tokens-per-hour: ${TIP_TOKENS_PER_HOUR:5}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:}

jwt:
  ttl-web: ${JWT_TTL_WEB:P30D}
  ttl-mobile: ${JWT_TTL_MOBILE:P30D}

python-compiler:
  api-url: ${PYTHON_COMPILER_API_URL:}
  api-token: ${PYTHON_COMPILER_API_TOKEN:}

clevertap:
  api-url: ${CLEVERTAP_API_URL:}
  api-project-header-name: ${CLEVERTAP_API_PROJECT_HEADER_NAME:}
  api-project-id: ${CLEVERTAP_API_PROJECT_ID:}
  api-passcode-header-name: ${CLEVERTAP_API_PASSCODE_HEADER_NAME:}
  api-passcode: ${CLEVERTAP_API_PASSCODE:}

ed-link:
  api-url: ${EDLINK_API_URL:}
  client-secret: ${EDLINK_API_CLIENT_SECRET:}
  client-id: ${EDLINK_API_CLIENT_ID:}
  redirect-uri: ${EDLINK_API_REDIRECT_URI:}

---

spring:
  config:
    activate:
      on-profile: stage

domains:
  web: edu-stage.imagilabs.com

integrations:
  google:
    sheets:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: prod

domains:
  web: edu.imagilabs.com

integrations:
  google:
    sheets:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: prod,stage

  mail:
    host: ${MAIL_HOST:}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true

email:
  no-reply-address: ${EMAIL_NO_REPLY_ADDRESS:}
