WITH
	STUDENT_DRAFT_PROJECTS AS (
		SELECT
			OWNER_ID,
			SPS.NAME AS NAME,
			SPS.USERNAME AS USERNAME,
			SPS.CLASSROOM_ID AS CLASSROOM_ID,
			COUNT(DISTINCT PR.ID) AS NUMBER_OF_DRAFT_PROJECTS
		FROM
			PROJECTS AS PR
			LEFT JOIN STUDENT_PROFILES AS SPS ON PR.OWNER_ID = SPS.ID
		WHERE
			PR.ID NOT IN (
				SELECT DISTINCT
					PROJECT_ID
				FROM
					PROJECT_CLASSROOM_SHARE
			)
			AND OWNER_USER_TYPE = 'STUDENT'
		GROUP BY
			OWNER_ID,
			SPS.NAME,
			SPS.USERNAME,
			SPS.CLASSROOM_ID
	),
	STUDENT_SHARED_PROJECTS AS (
		SELECT
			OWNER_ID,
			SPS.NAME AS NAME,
			SPS.USERNAME AS USERNAME,
			SPS.CLASSROOM_ID AS CLASSROOM_ID,
			COUNT(DISTINCT PCS.PROJECT_ID) AS NUMBER_OF_SHARED_PROJECTS
		FROM
			PROJECTS AS PR
			LEFT JOIN PROJECT_CLASSROOM_SHARE AS PCS ON PR.ID = PCS.PROJECT_ID
			LEFT JOIN STUDENT_PROFILES AS SPS ON PR.OWNER_ID = SPS.ID
		WHERE
			OWNER_USER_TYPE = 'STUDENT'
		GROUP BY
			OWNER_ID,
			SPS.NAME,
			SPS.USERNAME,
			SPS.CLASSROOM_ID
	),
	STUDENT_PROJECTS AS (
		SELECT
			COALESCE(
				STUDENT_DRAFT_PROJECTS.OWNER_ID,
				STUDENT_SHARED_PROJECTS.OWNER_ID
			) AS STUDENT_ID,
			COALESCE(
				STUDENT_DRAFT_PROJECTS.NAME,
				STUDENT_SHARED_PROJECTS.NAME
			) AS NAME,
			COALESCE(
				STUDENT_DRAFT_PROJECTS.USERNAME,
				STUDENT_SHARED_PROJECTS.USERNAME
			) AS USERNAME,
			COALESCE(
				STUDENT_DRAFT_PROJECTS.CLASSROOM_ID,
				STUDENT_SHARED_PROJECTS.CLASSROOM_ID
			) AS CLASSROOM_ID,
			NUMBER_OF_DRAFT_PROJECTS,
			NUMBER_OF_SHARED_PROJECTS
		FROM
			STUDENT_DRAFT_PROJECTS
			FULL OUTER JOIN STUDENT_SHARED_PROJECTS ON STUDENT_DRAFT_PROJECTS.OWNER_ID = STUDENT_SHARED_PROJECTS.OWNER_ID
	),
	CLASSROOM_INFO AS (
		SELECT
			CL.ID AS CLASSROOM_ID,
			CL.CREATED_AT AS CREATION_DATE,
			CL.TEACHER_ID AS TEACHER_ID,
			COUNT(DISTINCT STUDENT_PROFILES.ID) AS NUMBER_OF_STUDENTS,
			COALESCE(SUM(STUDENT_PROJECTS.NUMBER_OF_DRAFT_PROJECTS), 0) AS NUMBER_OF_DRAFT_PROJECTS,
			COALESCE(
				SUM(STUDENT_PROJECTS.NUMBER_OF_SHARED_PROJECTS),
				0
			) AS NUMBER_OF_SHARED_PROJECTS
		FROM
			STUDENT_PROFILES
			RIGHT JOIN CLASSROOMS AS CL ON STUDENT_PROFILES.CLASSROOM_ID = CL.ID
			LEFT JOIN STUDENT_PROJECTS ON STUDENT_PROFILES.ID = STUDENT_PROJECTS.STUDENT_ID
		GROUP BY
			CL.ID
	),
	TEACHER_PROFILE AS (
		SELECT
			TPS.ID AS TEACHER_ID,
			TPS.EMAIL AS EMAIL,
			TPS.CREATED_AT AS CREATION_DATE,
			COUNT(DISTINCT CR.ID) AS NUMBER_OF_CLASSES
		FROM
			TEACHER_PROFILES AS TPS
			LEFT JOIN CLASSROOMS AS CR ON TPS.ID = CR.TEACHER_ID
		GROUP BY
			TPS.ID,
			TPS.EMAIL
	),
	DRAFT_PROJECTS AS (
		SELECT
			OWNER_ID,
			TPS.EMAIL AS EMAIL,
			TPS.CREATED_AT AS CREATION_DATE,
			COUNT(DISTINCT PR.ID) AS NUMBER_OF_DRAFT_PROJECTS
		FROM
			PROJECTS AS PR
			LEFT JOIN TEACHER_PROFILES AS TPS ON PR.OWNER_ID = TPS.ID
		WHERE
			PR.ID NOT IN (
				SELECT DISTINCT
					PROJECT_ID
				FROM
					PROJECT_CLASSROOM_SHARE
			)
			AND PR.NAME NOT IN (
				'Example 1 [beginner]',
				'Example 2 [beginner]',
				'Example 3 [intermediate]',
				'Example 4 [intermediate]',
				'Example 5 [advanced]'
			)
			AND OWNER_USER_TYPE = 'TEACHER'
		GROUP BY
			OWNER_ID,
			TPS.EMAIL,
			TPS.CREATED_AT
	),
	SHARED_PROJECTS AS (
		SELECT
			OWNER_ID,
			TPS.EMAIL AS EMAIL,
			TPS.CREATED_AT AS CREATION_DATE,
			COUNT(DISTINCT PCS.PROJECT_ID) AS NUMBER_OF_SHARED_PROJECTS
		FROM
			PROJECTS AS PR
			LEFT JOIN PROJECT_CLASSROOM_SHARE AS PCS ON PR.ID = PCS.PROJECT_ID
			LEFT JOIN TEACHER_PROFILES AS TPS ON PR.OWNER_ID = TPS.ID
		WHERE
			OWNER_USER_TYPE = 'TEACHER'
		GROUP BY
			OWNER_ID,
			TPS.EMAIL,
			TPS.CREATED_AT
	),
	TEACHER_PROJECTS AS (
		SELECT
			COALESCE(DRAFT_PROJECTS.OWNER_ID, SHARED_PROJECTS.OWNER_ID) AS TEACHER_ID,
			COALESCE(DRAFT_PROJECTS.EMAIL, SHARED_PROJECTS.EMAIL) AS EMAIL,
			COALESCE(
				DRAFT_PROJECTS.CREATION_DATE,
				SHARED_PROJECTS.CREATION_DATE
			) AS CREATION_DATE,
			NUMBER_OF_DRAFT_PROJECTS,
			NUMBER_OF_SHARED_PROJECTS
		FROM
			DRAFT_PROJECTS
			FULL OUTER JOIN SHARED_PROJECTS ON DRAFT_PROJECTS.OWNER_ID = SHARED_PROJECTS.OWNER_ID
	)
SELECT
	TEACHER_PROFILES.ID AS TEACHER_ID,
	TEACHER_PROFILES.EMAIL AS EMAIL,
	TEACHER_PROFILES.CREATED_AT AS CREATION_DATE,
	TEACHER_PROFILES.EMAIL_VERIFIED AS EMAIL_VERIFIED,
	TEACHER_PROFILE.NUMBER_OF_CLASSES AS NUMBER_OF_CLASSES,
	COALESCE(TEACHER_PROJECTS.NUMBER_OF_DRAFT_PROJECTS, 0) AS NUMBER_OF_DRAFT_PROJECTS,
	COALESCE(TEACHER_PROJECTS.NUMBER_OF_SHARED_PROJECTS, 0) AS NUMBER_OF_SHARED_PROJECTS,
	COALESCE(SUM(CLASSROOM_INFO.NUMBER_OF_STUDENTS), 0) AS NUMBER_OF_STUDENTS,
	COALESCE(SUM(CLASSROOM_INFO.NUMBER_OF_DRAFT_PROJECTS), 0) AS NUMBER_OF_STUDENT_DRAFT_PROJECTS,
	COALESCE(SUM(CLASSROOM_INFO.NUMBER_OF_SHARED_PROJECTS), 0) AS NUMBER_OF_STUDENT_SHARED_PROJECTS
FROM
	TEACHER_PROFILES
	LEFT JOIN TEACHER_PROJECTS ON TEACHER_PROFILES.ID = TEACHER_PROJECTS.TEACHER_ID
	LEFT JOIN TEACHER_PROFILE ON TEACHER_PROFILES.ID = TEACHER_PROFILE.TEACHER_ID
	LEFT JOIN CLASSROOM_INFO ON TEACHER_PROFILES.ID = CLASSROOM_INFO.TEACHER_ID
GROUP BY
	TEACHER_PROFILES.ID,
	TEACHER_PROFILE.NUMBER_OF_CLASSES,
	TEACHER_PROJECTS.NUMBER_OF_DRAFT_PROJECTS,
	TEACHER_PROJECTS.NUMBER_OF_SHARED_PROJECTS
ORDER BY
	CREATION_DATE ASC