WITH
	STUDENT_DRAFT_PROJECTS AS (
		SELECT
			PR.OWNER_ID,
			SPS.NAME,
			SPS.USERNAME,
			SPS.CLASSROOM_ID,
			COUNT(DISTINCT PR.ID) AS NUMBER_OF_DRAFT_PROJECTS_ALL_TIME,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(TO_TIMESTAMP(PR.CREATED_AT / 1000), 'YYYY-MM-DD') >= '2024-06-01' THEN PR.ID
				END
			) AS NUMBER_OF_DRAFT_PROJECTS_CURRENT,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(TO_TIMESTAMP(PR.CREATED_AT / 1000), 'YYYY-MM-DD') BETWEEN '2023-06-01' AND '2024-05-31'  THEN PR.ID
				END
			) AS NUMBER_OF_DRAFT_PROJECTS_PREV
		FROM
			PROJECTS PR
			LEFT JOIN STUDENT_PROFILES SPS ON PR.OWNER_ID = SPS.ID
		WHERE
			PR.ID NOT IN (
				SELECT DISTINCT
					PROJECT_ID
				FROM
					PROJECT_CLASSROOM_SHARE
			)
			AND OWNER_USER_TYPE = 'STUDENT'
		GROUP BY
			PR.OWNER_ID,
			SPS.NAME,
			SPS.USERNAME,
			SPS.CLASSROOM_ID
	),
	STUDENT_SHARED_PROJECTS AS (
		SELECT
			PR.OWNER_ID,
			SPS.NAME,
			SPS.USERNAME,
			SPS.CLASSROOM_ID,
			COUNT(DISTINCT PR.ID) AS NUMBER_OF_SHARED_PROJECTS_ALL_TIME,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(TO_TIMESTAMP(PR.CREATED_AT / 1000), 'YYYY-MM-DD') >= '2024-06-01' THEN PR.ID
				END
			) AS NUMBER_OF_SHARED_PROJECTS_CURRENT,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(TO_TIMESTAMP(PR.CREATED_AT / 1000), 'YYYY-MM-DD') BETWEEN '2023-06-01' AND '2024-05-31'  THEN PR.ID
				END
			) AS NUMBER_OF_SHARED_PROJECTS_PREV
		FROM
			PROJECTS PR
			INNER JOIN PROJECT_CLASSROOM_SHARE PCS ON PR.ID = PCS.PROJECT_ID
			LEFT JOIN STUDENT_PROFILES SPS ON PR.OWNER_ID = SPS.ID
		WHERE
			OWNER_USER_TYPE = 'STUDENT'
		GROUP BY
			PR.OWNER_ID,
			SPS.NAME,
			SPS.USERNAME,
			SPS.CLASSROOM_ID
	),
	STUDENT_PROJECTS AS (
		SELECT
			COALESCE(SD.OWNER_ID, SS.OWNER_ID) AS STUDENT_ID,
			COALESCE(SD.NAME, SS.NAME) AS NAME,
			COALESCE(SD.USERNAME, SS.USERNAME) AS USERNAME,
			COALESCE(SD.CLASSROOM_ID, SS.CLASSROOM_ID) AS CLASSROOM_ID,
			SD.NUMBER_OF_DRAFT_PROJECTS_ALL_TIME,
			SD.NUMBER_OF_DRAFT_PROJECTS_CURRENT,
			SD.NUMBER_OF_DRAFT_PROJECTS_PREV,
			SS.NUMBER_OF_SHARED_PROJECTS_ALL_TIME,
			SS.NUMBER_OF_SHARED_PROJECTS_CURRENT,
			SS.NUMBER_OF_SHARED_PROJECTS_PREV
		FROM
			STUDENT_DRAFT_PROJECTS SD
			FULL OUTER JOIN STUDENT_SHARED_PROJECTS SS ON SD.OWNER_ID = SS.OWNER_ID
	),
	CLASSROOM_INFO AS (
		SELECT
			CL.ID AS CLASSROOM_ID,
			CL.CREATED_AT,
			CL.TEACHER_ID,
			COUNT(DISTINCT STUDENT_PROFILES.ID) AS NUMBER_OF_STUDENTS_ALL_TIME,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(
						TO_TIMESTAMP(STUDENT_PROFILES.CREATED_AT / 1000),
						'YYYY-MM-DD'
					) >= '2024-06-01' THEN STUDENT_PROFILES.ID
				END
			) AS NUMBER_OF_STUDENTS_CURRENT,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(
						TO_TIMESTAMP(STUDENT_PROFILES.CREATED_AT / 1000),
						'YYYY-MM-DD'
					) BETWEEN '2023-06-01' AND '2024-05-31'  THEN STUDENT_PROFILES.ID
				END
			) AS NUMBER_OF_STUDENTS_PREV,
			COALESCE(
				SUM(
					STUDENT_PROJECTS.NUMBER_OF_DRAFT_PROJECTS_ALL_TIME
				),
				0
			) AS NUMBER_OF_STUDENT_DRAFT_PROJECTS_ALL_TIME,
			COALESCE(
				SUM(STUDENT_PROJECTS.NUMBER_OF_DRAFT_PROJECTS_CURRENT),
				0
			) AS NUMBER_OF_STUDENT_DRAFT_PROJECTS_CURRENT,
			COALESCE(
				SUM(STUDENT_PROJECTS.NUMBER_OF_DRAFT_PROJECTS_PREV),
				0
			) AS NUMBER_OF_STUDENT_DRAFT_PROJECTS_PREV,
			COALESCE(
				SUM(
					STUDENT_PROJECTS.NUMBER_OF_SHARED_PROJECTS_ALL_TIME
				),
				0
			) AS NUMBER_OF_STUDENT_SHARED_PROJECTS_ALL_TIME,
			COALESCE(
				SUM(
					STUDENT_PROJECTS.NUMBER_OF_SHARED_PROJECTS_CURRENT
				),
				0
			) AS NUMBER_OF_STUDENT_SHARED_PROJECTS_CURRENT,
			COALESCE(
				SUM(STUDENT_PROJECTS.NUMBER_OF_SHARED_PROJECTS_PREV),
				0
			) AS NUMBER_OF_STUDENT_SHARED_PROJECTS_PREV
		FROM
			STUDENT_PROFILES
			RIGHT JOIN CLASSROOMS CL ON STUDENT_PROFILES.CLASSROOM_ID = CL.ID
			LEFT JOIN STUDENT_PROJECTS ON STUDENT_PROFILES.ID = STUDENT_PROJECTS.STUDENT_ID
		GROUP BY
			CL.ID,
			CL.CREATED_AT,
			CL.TEACHER_ID
	),
	TEACHER_PROFILE AS (
		SELECT
			TPS.ID AS TEACHER_ID,
			TPS.EMAIL,
			TPS.CREATED_AT,
			COUNT(DISTINCT CR.ID) AS NUMBER_OF_CLASSES_ALL_TIME,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(TO_TIMESTAMP(CR.CREATED_AT / 1000), 'YYYY-MM-DD') >= '2024-06-01' THEN CR.ID
				END
			) AS NUMBER_OF_CLASSES_CURRENT,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(TO_TIMESTAMP(CR.CREATED_AT / 1000), 'YYYY-MM-DD') BETWEEN '2023-06-01' AND '2024-05-31'  THEN CR.ID
				END
			) AS NUMBER_OF_CLASSES_PREV
		FROM
			TEACHER_PROFILES TPS
			LEFT JOIN CLASSROOMS CR ON TPS.ID = CR.TEACHER_ID
		GROUP BY
			TPS.ID,
			TPS.EMAIL,
			TPS.CREATED_AT
	),
	DRAFT_PROJECTS AS (
		SELECT
			PR.OWNER_ID,
			TPS.EMAIL,
			TPS.CREATED_AT,
			COUNT(DISTINCT PR.ID) AS NUMBER_OF_DRAFT_PROJECTS_ALL_TIME,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(TO_TIMESTAMP(PR.CREATED_AT / 1000), 'YYYY-MM-DD') >= '2024-06-01' THEN PR.ID
				END
			) AS NUMBER_OF_DRAFT_PROJECTS_CURRENT,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(TO_TIMESTAMP(PR.CREATED_AT / 1000), 'YYYY-MM-DD') BETWEEN '2023-06-01' AND '2024-05-31'  THEN PR.ID
				END
			) AS NUMBER_OF_DRAFT_PROJECTS_PREV
		FROM
			PROJECTS PR
			LEFT JOIN TEACHER_PROFILES TPS ON PR.OWNER_ID = TPS.ID
		WHERE
			PR.ID NOT IN (
				SELECT DISTINCT
					PROJECT_ID
				FROM
					PROJECT_CLASSROOM_SHARE
			)
			AND PR.NAME NOT IN (
				'Example 1 [beginner]',
				'Example 2 [beginner]',
				'Example 3 [intermediate]',
				'Example 4 [intermediate]',
				'Example 5 [advanced]'
			)
			AND OWNER_USER_TYPE = 'TEACHER'
		GROUP BY
			PR.OWNER_ID,
			TPS.EMAIL,
			TPS.CREATED_AT
	),
	SHARED_PROJECTS AS (
		SELECT
			PR.OWNER_ID,
			TPS.EMAIL,
			TPS.CREATED_AT,
			COUNT(DISTINCT PR.ID) AS NUMBER_OF_SHARED_PROJECTS_ALL_TIME,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(TO_TIMESTAMP(PR.CREATED_AT / 1000), 'YYYY-MM-DD') >= '2024-06-01' THEN PR.ID
				END
			) AS NUMBER_OF_SHARED_PROJECTS_CURRENT,
			COUNT(
				DISTINCT CASE
					WHEN TO_CHAR(TO_TIMESTAMP(PR.CREATED_AT / 1000), 'YYYY-MM-DD') BETWEEN '2023-06-01' AND '2024-05-31'  THEN PR.ID
				END
			) AS NUMBER_OF_SHARED_PROJECTS_PREV
		FROM
			PROJECTS PR
			INNER JOIN PROJECT_CLASSROOM_SHARE PCS ON PR.ID = PCS.PROJECT_ID
			LEFT JOIN TEACHER_PROFILES TPS ON PR.OWNER_ID = TPS.ID
		WHERE
			OWNER_USER_TYPE = 'TEACHER'
		GROUP BY
			PR.OWNER_ID,
			TPS.EMAIL,
			TPS.CREATED_AT
	),
	TEACHER_PROJECTS AS (
		SELECT
			COALESCE(DP.OWNER_ID, SP.OWNER_ID) AS TEACHER_ID,
			COALESCE(DP.EMAIL, SP.EMAIL) AS EMAIL,
			COALESCE(DP.CREATED_AT, SP.CREATED_AT) AS CREATION_DATE,
			DP.NUMBER_OF_DRAFT_PROJECTS_ALL_TIME,
			DP.NUMBER_OF_DRAFT_PROJECTS_CURRENT,
			DP.NUMBER_OF_DRAFT_PROJECTS_PREV,
			SP.NUMBER_OF_SHARED_PROJECTS_ALL_TIME,
			SP.NUMBER_OF_SHARED_PROJECTS_CURRENT,
			SP.NUMBER_OF_SHARED_PROJECTS_PREV
		FROM
			DRAFT_PROJECTS DP
			FULL OUTER JOIN SHARED_PROJECTS SP ON DP.OWNER_ID = SP.OWNER_ID
	)
SELECT
	TP.ID AS TEACHER_ID,
	TP.EMAIL,
	TP.CREATED_AT,
	TP.EMAIL_VERIFIED,
	TPROF.NUMBER_OF_CLASSES_ALL_TIME,
	COALESCE(TPROJ.NUMBER_OF_DRAFT_PROJECTS_ALL_TIME, 0) AS NUMBER_OF_DRAFT_PROJECTS_ALL_TIME,
	COALESCE(TPROJ.NUMBER_OF_SHARED_PROJECTS_ALL_TIME, 0) AS NUMBER_OF_SHARED_PROJECTS_ALL_TIME,
	COALESCE(SUM(CI.NUMBER_OF_STUDENTS_ALL_TIME), 0) AS NUMBER_OF_STUDENTS_ALL_TIME,
	COALESCE(
		SUM(CI.NUMBER_OF_STUDENT_DRAFT_PROJECTS_ALL_TIME),
		0
	) AS NUMBER_OF_STUDENT_DRAFT_PROJECTS_ALL_TIME,
	COALESCE(
		SUM(CI.NUMBER_OF_STUDENT_SHARED_PROJECTS_ALL_TIME),
		0
	) AS NUMBER_OF_STUDENT_SHARED_PROJECTS_ALL_TIME,
	TPROF.NUMBER_OF_CLASSES_CURRENT,
	COALESCE(TPROJ.NUMBER_OF_DRAFT_PROJECTS_CURRENT, 0) AS NUMBER_OF_DRAFT_PROJECTS_CURRENT,
	COALESCE(TPROJ.NUMBER_OF_SHARED_PROJECTS_CURRENT, 0) AS NUMBER_OF_SHARED_PROJECTS_CURRENT,
	COALESCE(SUM(CI.NUMBER_OF_STUDENTS_CURRENT), 0) AS NUMBER_OF_STUDENTS_CURRENT,
	COALESCE(
		SUM(CI.NUMBER_OF_STUDENT_DRAFT_PROJECTS_CURRENT),
		0
	) AS NUMBER_OF_STUDENT_DRAFT_PROJECTS_CURRENT,
	COALESCE(
		SUM(CI.NUMBER_OF_STUDENT_SHARED_PROJECTS_CURRENT),
		0
	) AS NUMBER_OF_STUDENT_SHARED_PROJECTS_CURRENT,
	TPROF.NUMBER_OF_CLASSES_PREV,
	COALESCE(TPROJ.NUMBER_OF_DRAFT_PROJECTS_PREV, 0) AS NUMBER_OF_DRAFT_PROJECTS_PREV,
	COALESCE(TPROJ.NUMBER_OF_SHARED_PROJECTS_PREV, 0) AS NUMBER_OF_SHARED_PROJECTS_PREV,
	COALESCE(SUM(CI.NUMBER_OF_STUDENTS_PREV), 0) AS NUMBER_OF_STUDENTS_PREV,
	COALESCE(SUM(CI.NUMBER_OF_STUDENT_DRAFT_PROJECTS_PREV), 0) AS NUMBER_OF_STUDENT_DRAFT_PROJECTS_PREV,
	COALESCE(SUM(CI.NUMBER_OF_STUDENT_SHARED_PROJECTS_PREV), 0) AS NUMBER_OF_STUDENT_SHARED_PROJECTS_PREV
FROM
	TEACHER_PROFILES TP
	LEFT JOIN TEACHER_PROJECTS TPROJ ON TP.ID = TPROJ.TEACHER_ID
	LEFT JOIN TEACHER_PROFILE TPROF ON TP.ID = TPROF.TEACHER_ID
	LEFT JOIN CLASSROOM_INFO CI ON TP.ID = CI.TEACHER_ID
GROUP BY
	TP.ID,
	TPROF.NUMBER_OF_CLASSES_ALL_TIME,
	TPROF.NUMBER_OF_CLASSES_CURRENT,
	TPROF.NUMBER_OF_CLASSES_PREV,
	TPROJ.NUMBER_OF_DRAFT_PROJECTS_ALL_TIME,
	TPROJ.NUMBER_OF_DRAFT_PROJECTS_CURRENT,
	TPROJ.NUMBER_OF_DRAFT_PROJECTS_PREV,
	TPROJ.NUMBER_OF_SHARED_PROJECTS_ALL_TIME,
	TPROJ.NUMBER_OF_SHARED_PROJECTS_CURRENT,
	TPROJ.NUMBER_OF_SHARED_PROJECTS_PREV,
	TP.EMAIL,
	TP.CREATED_AT,
	TP.EMAIL_VERIFIED
ORDER BY
	TP.CREATED_AT ASC