package com.anahoret.imagilabsapi.teachers.domain

enum class SchoolRole {
    ADMINISTRATOR,
    COACH,
    COORDINATOR,
    CURRICULUM_SPECIALIST,
    DISTRICT_ADMINISTRATOR,
    GIFTED_AND_TALENTED,
    GUARDIAN,
    HOMESCHOOL,
    LIBRARIAN_MEDIA_SPECIALIST,
    OBSERVER,
    STAFF,
    SUPERINTENDENT_ASSISTANT_SUPERINTENDENT,
    TEACHER,
    TECH_OR_STEM_COORDINATOR,
    OTHER
}