version: '3.2'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: imagilabs # Database name
      POSTGRES_USER: imagilabs # Database user name
      POSTGRES_PASSWORD: imagilabs # Database user password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data # Store Postgres data ./pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
